### ISSUE TITLE
`--aws-profile` doesn't honor `default`

### ISSUE THREAD

**Issue by mrchief** [dowjones/tokendito#64]
`tokendito --aws-profile default ...` doesn't create `default` profile. It takes the role profile instead. So if the role arn is `role_arn = arn:aws:iam::1234:role/foo-admin`, then the profile is `foo-admin` instead of `default` in `.aws/config`

**Comment by mrchief** [comment]
@pcmxgti I think it happens if you already have `AWS_PROFILE` env var set. I tried in a fresh shell and it works but as soon as I `export AWS_PROFILE=foo_admin` , it doesn't work anymore. Not sure if that's the behavior to keep. If so, we'd need to make a not in the docs.

**Comment by taschmidt** [comment]
I ran into this too. It's not even a question of the `default` okta profile, the `AWS_PROFILE` env var seems to completely override the `aws-profile` param (even when explicitly passed in via CLI). I can't see where this would be the desired behavior.

For now I'll go back to using the `AWS_DEFAULT_PROFILE` env var instead but that isn't ideal either since some AWS code doesn't honor that, even though it's right in their own docs 🙄.

**Comment by pcmxgti** [comment]
@mrchief this has been fixed and was recently merged to `main` in #99
